config/routes.rb
Rails.application.routes.draw do
  resources :magazines
  resources :oenologists
  devise_for :users
  resources :strains
  resources :wines
  root 'wines#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :assemblies
    has_many :strains, through: :assemblies
    has_many :wine_scores
    has_many :oenologists, through: :wine_scores
    accepts_nested_attributes_for :assemblies, :wine_scores, reject_if: :all_blank
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  #skip_before_action :authenticate_user!
  #skip_before_action :only_admin

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @wine.assemblies.build
    @strains = Strain.all
    @strains_two = Strain.pluck :name, :id
    @oenologists = Oenologist.all  
  end

  # GET /wines/1/edit
  def edit
    @wine.wine_scores.build
    @strains = Strain.all
    @strains_two = Strain.pluck :name, :id
    @oenologists = Oenologist.all
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, {assemblies_attributes:[:id, :strain_id, :percentage]}, {wine_scores_attributes: [:oenologist_id, :wine_id, :score]})
    end

    def not_admin
      redirect_to root_path, alert: "Solo Peter puede ver esta cuestión" and return if !current_user.admin
    end
    
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_assembly_fields.html.erb
<div class="field">
    <%= f.label :strain_id %>
    <%= f.select :strain_id, options_for_select(@strains_two) %> 
</div>

<div class="field">
    <%= f.label :percentage %>
    <%= f.number_field :percentage %>
</div>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.fields_for :assemblies do |ff| %>
      <%= render 'assembly_fields', f: ff %>
    <% end %>
  </div>

  <div class="links">
    <%= link_to_add_association 'Otra cepa', form, :assemblies %>
  </div>

  <div class="field">
    <%= form.fields_for :wine_scores do |ff| %>
      <%= render 'wine_score_fields', f: ff %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wine_score_fields.html.erb
<div class="field">
    <%= f.label :oenologist_id %>
    <%= f.collection_select :oenologist_id, @oenologists, :id, :name %>
</div>

<div class="field">
    <%= f.label :score %>
    <%= f.number_field :score %>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>
<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Strains</th>
      <th>Percentage</th>
      <th>Score</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td>
          <ul>
              <% wine.assemblies.each do |assembly| %>
                <li><%= assembly.strain.name %> (<%=assembly.percentage  %>%)</li>
              <% end %>
          </ul>
        </td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>
<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>